spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${CLIENT_SECRET}
            clientSecret: ${CLIENT_SECRET}
  jpa:
    defer-datasource-initialization: true
  